// angular/src/app/app.component.ts
import { Component } from '@angular/core';
// @ts-ignore
import emoji from "node-emoji"
import EmojiTs from "./Emoji"

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title:String = 'angular-app';
  randomEmoji:EmojiTs
  searchText:String = ''
  emojiList:Array<EmojiTs> = []
  constructor() {
    this.randomEmoji = (emoji.random())
   }
   searchTextChange(){
    let { searchText } = this || {};
    let emojiSearch = searchText.toLowerCase();
    if (searchText !== "") {
      this.emojiList = emoji.search(emojiSearch);
    } else {
      this.emojiList = [];
    }
    console.log(this.emojiList)
   }
}

<div class="App">
  <h1>Emoji Search App {{ randomEmoji.emoji }}</h1>
  <div class="search-container">
    <input
      placeholder="Enter a emoji name to search"
      [(ngModel)]="searchText"
      (input)="searchTextChange()"
    />
    <app-emoji-result [emojiList]="emojiList"></app-emoji-result>
  </div>
</div>

// react/src/App.js
import "./App.css";
import emoji from "node-emoji";
import { useEffect, useState } from "react";
import EmojiResult from "./components/EmojiResult";

function App() {
  const [search, setSearch] = useState("");
  const [emojiList, setEmojiList] = useState([]);
  const [randomEmoji, setRandomEmoji] = useState({});

  useEffect(() => {
    setRandomEmoji(emoji.random());
  }, []);
  const onSearchTextChange = (newValue) => {
    let searchValue = newValue.target.value;
    let emojiSearch = searchValue.toLowerCase();
    setSearch(searchValue);
    if (searchValue !== "") {
      setEmojiList(emoji.search(emojiSearch));
    } else {
      setEmojiList([]);
    }
  };
  return (
    <div className="App">
      <h1>Emoji Search App {randomEmoji.emoji}</h1>
      <div className="search-container">
        <input
          placeholder="Enter a emoji name to search"
          value={search}
          onInput={onSearchTextChange}
        />
        <EmojiResult emojiList={emojiList} />
      </div>
    </div>
  );
}

export default App;
